var productsItems = [
  {
    productId: 0,
    productLineId: 0,
    category: 0,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    productId: 1,
    productLineId: 0,
    category: 0,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    productId: 2,
    productLineId: 0,
    category: 0,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    productId: 3,
    productLineId: 0,
    category: 0,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    productId: 4,
    productLineId: 1,
    category: 1,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    productId: 5,
    productLineId: 1,
    category: 1,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    productId: 6,
    productLineId: 1,
    category: 1,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    productId: 7,
    productLineId: 1,
    category: 1,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    productId: 8,
    productLineId: 1,
    category: 1,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    productId: 9,
    productLineId: 2,
    category: 0,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    productId: 10,
    productLineId: 2,
    category: 0,
    status: 0,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    productId: 11,
    productLineId: 2,
    category: 0,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    productId: 12,
    productLineId: 2,
    category: 0,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    productId: 13,
    productLineId: 2,
    category: 0,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    productId: 14,
    productLineId: 3,
    category: 2,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    productId: 15,
    productLineId: 3,
    category: 2,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    productId: 16,
    productLineId: 3,
    category: 2,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    productId: 17,
    productLineId: 3,
    category: 2,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    productId: 18,
    productLineId: 3,
    category: 2,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    productId: 19,
    productLineId: 4,
    category: 2,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    productId: 20,
    productLineId: 4,
    category: 2,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    productId: 21,
    productLineId: 4,
    category: 2,
    status: 2,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    productId: 22,
    productLineId: 4,
    category: 2,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 23,
    productLineId: 5,
    category: 2,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 24,
    productLineId: 5,
    category: 2,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 25,
    productLineId: 5,
    category: 2,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 26,
    productLineId: 5,
    category: 2,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 27,
    productLineId: 6,
    category: 0,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 28,
    productLineId: 6,
    category: 0,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 29,
    productLineId: 6,
    category: 0,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 30,
    productLineId: 6,
    category: 0,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 31,
    productLineId: 7,
    category: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 32,
    productLineId: 7,
    category: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 33,
    productLineId: 7,
    category: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 34,
    productLineId: 7,
    category: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 35,
    productLineId: 8,
    category: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 36,
    productLineId: 8,
    category: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 37,
    productLineId: 8,
    category: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    productId: 38,
    productLineId: 8,
    category: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
];

var productLine = [
  {
    productLineId: 0,
    name: "Laptop Dell Inspiron T7420 N4I5021W",
    image: "../../../image/pc_sample.png",
    category: "Dell Inspiron",
  },
  {
    productLineId: 1,
    name: "Laptop Dell Vostro 3405",
    image: "../../../image/pc_sample.png",
    category: "Dell Vostro",
  },
  {
    productLineId: 2,
    name: "Laptop Dell Inspiron 16 5625 99VP91",
    image: "../../../image/pc_sample.png",
    category: "Dell Inspiron",
  },
  {
    productLineId: 3,
    name: "Laptop Dell XPS 13 Plus 9320 5CG56",
    image: "../../../image/pc_sample.png",
    category: "Dell XPS",
  },
  {
    productLineId: 4,
    name: "Laptop Dell XPS 15 9520 70295790",
    image: "../../../image/pc_sample.png",
    category: "Dell XPS",
  },
  {
    productLineId: 5,
    name: "Laptop Dell XPS 13 9320 70295789",
    image: "../../../image/pc_sample.png",
    category: "Dell XPS",
  },
  {
    productLineId: 6,
    name: "Dell Inspiron 5620 N6I7110W1",
    image: "../../../image/pc_sample.png",
    category: "Dell Inspiron",
  },
  {
    productLineId: 7,
    name: "Laptop Dell Vostro 13 5320 M32DH1",
    image: "../../../image/pc_sample.png",
    category: "Dell Vostro",
  },
  {
    productLineId: 8,
    name: "Laptop Dell Vostro 5320 V3I7005W",
    image: "../../../image/pc_sample.png",
    category: "Dell Vostro",
  },
];

const category = ["Dell Inspiron", "Dell Vostro", "Dell XPS"];

const status = [
  "NEW",
  "AGENCY",
  "SOLD",
  "ERROR_INSURANCE",
  "FIXING",
  "REFURBISHED",
  "RETURN_CUSTOMER",
  "ERROR_FACTORY",
  "ERROR_RETURN_FACTORY",
  "ERROR_WIDE",
  "OUT_OF_WARRANTY",
  "CANNOT_SELL",
];

const agency = ["agency_1", "agency_2", "agency_3", "agency_4", "agency_5"];

const factory = [
  "factory_1",
  "factory_2",
  "factory_3",
  "factory_4",
  "factory_5",
];

const insuarance = [
  "insuarance_1",
  "insuarance_2",
  "insuarance_3",
  "insuarance_4",
  "insuarance_5",
];

function getItems() {
  return productsItems;
}

function setItems(newItems) {
  productsItems = newItems;
}

export {
  getItems,
  setItems,
  productLine,
  status,
  agency,
  category,
  factory,
  insuarance,
};
