var deviceItems = [
  {
    deviceId: 0,
    productId: 0,
    productLine: 0,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    deviceId: 1,
    productId: 0,
    productLine: 0,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    deviceId: 2,
    productId: 0,
    productLine: 0,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    deviceId: 3,
    productId: 0,
    productLine: 0,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    deviceId: 4,
    productId: 1,
    productLine: 1,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    deviceId: 5,
    productId: 1,
    productLine: 1,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    deviceId: 6,
    productId: 1,
    productLine: 1,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    deviceId: 7,
    productId: 1,
    productLine: 1,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    deviceId: 8,
    productId: 1,
    productLine: 1,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    deviceId: 9,
    productId: 2,
    productLine: 0,
    status: 0,
    factory: -1,
    agency: 1,
    insuarance: -1,
  },
  {
    deviceId: 10,
    productId: 2,
    productLine: 0,
    status: 0,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    deviceId: 11,
    productId: 2,
    productLine: 0,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    deviceId: 12,
    productId: 2,
    productLine: 0,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    deviceId: 13,
    productId: 2,
    productLine: 0,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    deviceId: 14,
    productId: 3,
    productLine: 2,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    deviceId: 15,
    productId: 3,
    productLine: 2,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    deviceId: 16,
    productId: 3,
    productLine: 2,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    deviceId: 17,
    productId: 3,
    productLine: 2,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    deviceId: 18,
    productId: 3,
    productLine: 2,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    deviceId: 19,
    productId: 4,
    productLine: 2,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    deviceId: 20,
    productId: 4,
    productLine: 2,
    status: 1,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    deviceId: 21,
    productId: 4,
    productLine: 2,
    status: 2,
    factory: 1,
    agency: -1,
    insuarance: -1,
  },
  {
    deviceId: 22,
    productId: 4,
    productLine: 2,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 23,
    productId: 5,
    productLine: 2,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 24,
    productId: 5,
    productLine: 2,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 25,
    productId: 5,
    productLine: 2,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 26,
    productId: 5,
    productLine: 2,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 27,
    productId: 6,
    productLine: 0,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 28,
    productId: 6,
    productLine: 0,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 29,
    productId: 6,
    productLine: 0,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 30,
    productId: 6,
    productLine: 0,
    status: 2,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 31,
    productId: 7,
    productLine: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 32,
    productId: 7,
    productLine: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 33,
    productId: 7,
    productLine: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 34,
    productId: 7,
    productLine: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 35,
    productId: 8,
    productLine: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 36,
    productId: 8,
    productLine: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 37,
    productId: 8,
    productLine: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
  {
    deviceId: 38,
    productId: 8,
    productLine: 1,
    status: 3,
    factory: -1,
    agency: -1,
    insuarance: 1,
  },
];

var product = [
  {
    productId: 0,
    name: "Laptop Dell Inspiron T7420 N4I5021W",
    image: "../../../image/pc_sample.png",
    productLine: 0,
  },
  {
    productId: 1,
    name: "Laptop Dell Vostro 3405",
    image: "../../../image/pc_sample.png",
    productLine: 1,
  },
  {
    productId: 2,
    name: "Laptop Dell Inspiron 16 5625 99VP91",
    image: "../../../image/pc_sample.png",
    productLine: 0,
  },
  {
    productId: 3,
    name: "Laptop Dell XPS 13 Plus 9320 5CG56",
    image: "../../../image/pc_sample.png",
    productLine: 2,
  },
  {
    productId: 4,
    name: "Laptop Dell XPS 15 9520 70295790",
    image: "../../../image/pc_sample.png",
    productLine: 2,
  },
  {
    productId: 5,
    name: "Laptop Dell XPS 13 9320 70295789",
    image: "../../../image/pc_sample.png",
    productLine: 2,
  },
  {
    productId: 6,
    name: "Dell Inspiron 5620 N6I7110W1",
    image: "../../../image/pc_sample.png",
    productLine: 0,
  },
  {
    productId: 7,
    name: "Laptop Dell Vostro 13 5320 M32DH1",
    image: "../../../image/pc_sample.png",
    productLine: 1,
  },
  {
    productId: 8,
    name: "Laptop Dell Vostro 5320 V3I7005W",
    image: "../../../image/pc_sample.png",
    productLine: 1,
  },
];

const productLine = ["Dell Inspiron", "Dell Vostro", "Dell XPS"];

const status = [
  "NEW",
  "AGENCY",
  "SOLD",
  "ERROR_INSURANCE",
  "FIXING",
  "REFURBISHED",
  "RETURN_CUSTOMER",
  "ERROR_FACTORY",
  "ERROR_RETURN_FACTORY",
  "ERROR_WIDE",
  "OUT_OF_WARRANTY",
  "CANNOT_SELL",
];

const agency = ["agency_1", "agency_2", "agency_3", "agency_4", "agency_5"];

const factory = [
  "factory_1",
  "factory_2",
  "factory_3",
  "factory_4",
  "factory_5",
];

const insuarance = [
  "insuarance_1",
  "insuarance_2",
  "insuarance_3",
  "insuarance_4",
  "insuarance_5",
];

function getItems() {
  return deviceItems;
}

function setItems(newItems) {
  deviceItems = newItems;
}

export {
  getItems,
  setItems,
  product,
  status,
  agency,
  productLine,
  factory,
  insuarance,
};
